spring:  jpa:    properties:      dialect: org.hibernate.dialect.PostgreSQLDialect      hibernate:         globally_quoted_identifiers: true    hibernate:      ddl-auto: update    show-sql: true  datasource:    url: jdbc:postgresql://localhost:5432/travel-tracer
    username: postgres
    password: admin    